baseURL = "https://stronginteractions.github.io/"
languageCode = "en-us"
title = "Strong Interactions Podcast—Stories straight from the heart of matter"

theme = "zen"

[params]
mainSections = [
    "episodes",
    ""
]
copyright = "© 2022 Strong Interactions Podcast"
footer = "Powered by [Hugo](https://gohugo.io/), the [Zen theme](https://github.com/frjo/hugo-theme-zen), and opportunely manipulated charged leptons."
sidebar = true

[params.podcast]
title = "Strong Interactions"
description = "A podcast about exploring a new frontier in nuclear physics at the upcoming Electron-Ion Collider, by Maria Zurek and Markus Diefenthaler"
explicit = false
type = "episodic"
local = true
spotify = "https://open.spotify.com/show/6VsBMUrgv5kRxSapu16fF6"
amazon = "https://music.amazon.com/podcasts/c25725bb-194f-430d-908e-d7d447b9334e"
google = ""
apple = "https://podcasts.apple.com/us/podcast/strong-interactions/id1640110611"
